/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itheima_alipay_MainActivity */

#ifndef _Included_com_itheima_alipay_MainActivity
#define _Included_com_itheima_alipay_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itheima_alipay_MainActivity
 * Method:    safePay
 * Signature: (Ljava/lang/String;Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_itheima_alipay_MainActivity_safePay
  (JNIEnv *, jobject, jstring, jstring, jfloat);

#ifdef __cplusplus
}
#endif
#endif
